### PR TITLE
Add ESLint for CodeQuality Tools

### PR DESCRIPTION
**Pull request by odenktools**
Helloo @jondubois im added eslint for codequality, what do you think?

### CODE REVIEW

**Comment by jondubois** [comment]
@odenktools I think this might be useful at some point in the future, but for now I'd prefer to wait  a bit before introducing more dependencies to solve a problem which doesn't exist yet.

Contributors so far have been adhering to the code conventions and styling and so I don't feel that it's something that needs to be automated at this stage.

I'm happy to leave this PR open to revisit at a later date.
If anyone feels strongly about this PR, please leave a comment below.

I'd be happy to merge this is enough people feel that it's a problem for them.

**Comment by odenktools** [comment]
Sorry @jondubois for late reply.. ok great thinks! i hope all contributors like this PR.

**Comment by jondubois** [comment]
Glad that this didn't get merged https://github.com/eslint/eslint-scope/issues/39 ;p

**Comment by odenktools** [comment]
Yes its very very lucky :+1:

**Comment by jondubois** [comment]
@odenktools I still think we can consider ESLint but I think that the lesson is that we should be careful about adding too many dependencies to a project - There's a hidden risk/cost.

**Comment by odenktools** [comment]
@jondubois Thanks for lesson, yes i aggree with you, too many dependencies make project more complicated

**Pull request closed without merging**
